#!/usr/bin/env tsx
/**
 * Interactive setup CLI for Readable.
 *
 *   pnpm setup
 *
 * Detects which LLM providers are usable on this machine — by reading
 * env vars (.env.local + process env) plus CLI auth files
 * (~/.codex/auth.json, ~/.claude/.credentials.json, etc.) — then asks
 * the user to pick a primary provider and an optional fallback chain.
 * Writes the choices into .env.local.
 *
 * If a provider is picked but its credential isn't yet present, the
 * tool prints a one-line install hint (`getInstallHint`) and offers to
 * accept a pasted API key.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin, stdout } from "node:process";

import { config as loadDotenv } from "dotenv";

loadDotenv({ path: ".env.local" });
loadDotenv();

import {
  buildAuthProfileStore,
  getInstallHint,
  hasAnyProviderKey,
  listAvailableProviders,
  type ProviderAvailability,
  type RoutingProviderId,
} from "@/server/llm/routing";
import {
  listAvailableLocalCodingAgents,
  type CodingAgentId,
} from "@/server/llm";

const ENV_FILE = path.join(process.cwd(), ".env.local");

const SUPPORTED_PROVIDERS: RoutingProviderId[] = [
  "coding-agent",
  "anthropic",
  "openai",
  "openai-codex",
  "gemini",
  "google-vertex",
  "openrouter",
];

const PROVIDER_LABELS: Partial<Record<RoutingProviderId, string>> = {
  "coding-agent": "Local coding-agent CLIs (coding-agent)",
  anthropic: "Anthropic Claude (anthropic)",
  openai: "OpenAI GPT (openai)",
  "openai-codex": "OpenAI via Codex CLI subscription (openai-codex)",
  gemini: "Google Gemini API (gemini)",
  "google-vertex": "Google Vertex AI / gcloud ADC (google-vertex)",
  openrouter: "OpenRouter (free + paid models) (openrouter)",
};

function providerLabel(provider: RoutingProviderId): string {
  return PROVIDER_LABELS[provider] ?? provider;
}

/**
 * Providers we have an SDK class or local provider for today. Others are
 * detected but not selectable as primary. Order keeps OpenRouter first for
 * API-key setups, while exposing local coding-agent mode for no-key dev runs.
 */
const ROUTABLE_PROVIDERS: RoutingProviderId[] = [
  "openrouter",
  "coding-agent",
  "anthropic",
  "openai",
  "gemini",
];

const ENV_KEY_FOR_PROVIDER: Partial<Record<RoutingProviderId, string>> = {
  anthropic: "ANTHROPIC_API_KEY",
  openai: "OPENAI_API_KEY",
  gemini: "GEMINI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
};

interface AvailabilityRow {
  provider: RoutingProviderId;
  hasCli: boolean;
  hasEnv: boolean;
  available: ProviderAvailability | undefined;
  localAgents?: CodingAgentId[];
}

async function describeAvailability(): Promise<AvailabilityRow[]> {
  const store = await buildAuthProfileStore();
  const available = listAvailableProviders(store);
  const byProvider = new Map(available.map((entry) => [entry.provider, entry]));
  const localAgents = listAvailableLocalCodingAgents().map((entry) => entry.agent);
  return SUPPORTED_PROVIDERS.map((provider) => ({
    provider,
    hasCli:
      provider === "coding-agent"
        ? localAgents.length > 0
        : (byProvider.get(provider)?.hasCli ?? false),
    hasEnv:
      provider === "coding-agent"
        ? false
        : (byProvider.get(provider)?.hasEnv ?? hasAnyProviderKey(provider)),
    available: byProvider.get(provider),
    localAgents: provider === "coding-agent" ? localAgents : undefined,
  }));
}

function statusBadge(row: AvailabilityRow): string {
  if (row.provider === "coding-agent") {
    return row.localAgents && row.localAgents.length > 0
      ? `local CLI: ${row.localAgents.join(",")}`
      : "— missing local CLI —";
  }
  if (row.hasCli && row.hasEnv) return "CLI + env";
  if (row.hasCli) return "CLI";
  if (row.hasEnv) return "env";
  return "— missing —";
}

function printAvailabilityTable(rows: AvailabilityRow[]): void {
  const longestLabel = Math.max(...rows.map((r) => providerLabel(r.provider).length));
  console.log("\nDetected providers:");
  for (const row of rows) {
    const label = providerLabel(row.provider).padEnd(longestLabel + 2);
    const badge = statusBadge(row);
    const marker = row.hasCli || row.hasEnv ? "✓" : " ";
    console.log(`  ${marker} ${label}${badge}`);
  }
  console.log("");
}

async function readEnvFile(): Promise<string> {
  try {
    return await fs.readFile(ENV_FILE, "utf-8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return "# Generated by `pnpm setup` — see .env.local.example for the full reference.\n";
    }
    throw error;
  }
}

function upsertEnvLine(content: string, key: string, value: string): string {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`^${escaped}=.*$`, "m");
  const next = `${key}=${value}`;
  if (pattern.test(content)) {
    return content.replace(pattern, next);
  }
  const sep = content.endsWith("\n") || content.length === 0 ? "" : "\n";
  return `${content}${sep}${next}\n`;
}

async function writeEnvFile(content: string): Promise<void> {
  await fs.writeFile(ENV_FILE, content, { mode: 0o600 });
}

async function promptChoice(
  rl: readline.Interface,
  question: string,
  options: string[],
  defaultIndex = 0,
): Promise<number> {
  console.log(question);
  options.forEach((option, idx) => {
    const marker = idx === defaultIndex ? "›" : " ";
    console.log(`  ${marker} [${idx + 1}] ${option}`);
  });
  while (true) {
    const raw = (
      await rl.question(`Pick [1-${options.length}] (default ${defaultIndex + 1}): `)
    ).trim();
    if (raw === "") return defaultIndex;
    const numeric = Number(raw);
    if (Number.isInteger(numeric) && numeric >= 1 && numeric <= options.length) {
      return numeric - 1;
    }
    console.log("  ⚠ please enter a number from the list.");
  }
}

async function promptYesNo(
  rl: readline.Interface,
  question: string,
  defaultYes = true,
): Promise<boolean> {
  const hint = defaultYes ? "Y/n" : "y/N";
  while (true) {
    const raw = (await rl.question(`${question} [${hint}]: `)).trim().toLowerCase();
    if (raw === "") return defaultYes;
    if (raw === "y" || raw === "yes") return true;
    if (raw === "n" || raw === "no") return false;
    console.log("  ⚠ please answer y or n.");
  }
}

async function promptApiKey(
  rl: readline.Interface,
  envName: string,
  install: string | undefined,
): Promise<string | undefined> {
  if (install) {
    console.log(`  Hint: ${install}`);
  }
  console.log(`  Paste your ${envName} below (or press enter to skip).`);
  const raw = (await rl.question(`  ${envName}=`)).trim();
  if (raw.length === 0) return undefined;
  return raw;
}

async function pickPrimary(
  rl: readline.Interface,
  rows: AvailabilityRow[],
): Promise<RoutingProviderId> {
  const labels = ROUTABLE_PROVIDERS.map((provider) => {
    const row = rows.find((r) => r.provider === provider);
    const status = row ? statusBadge(row) : "missing";
    return `${providerLabel(provider)} — ${status}`;
  });
  const idx = await promptChoice(
    rl,
    "\nPick a primary provider for chat / summary / Q&A:",
    labels,
    Math.max(
      0,
      ROUTABLE_PROVIDERS.findIndex(
        (p) =>
          rows.find((r) => r.provider === p)?.hasCli || rows.find((r) => r.provider === p)?.hasEnv,
      ),
    ),
  );
  return ROUTABLE_PROVIDERS[idx];
}

async function pickFallbacks(
  rl: readline.Interface,
  primary: RoutingProviderId,
  rows: AvailabilityRow[],
): Promise<RoutingProviderId[]> {
  if (primary === "coding-agent") {
    console.log("\nLocal coding-agent mode uses LLM_LOCAL_AGENTS for CLI fallback order.");
    return [];
  }
  const candidates = ROUTABLE_PROVIDERS.filter((p) => p !== primary).filter(
    (p) =>
      p !== "coding-agent" &&
      (rows.find((r) => r.provider === p)?.hasCli || rows.find((r) => r.provider === p)?.hasEnv),
  );
  if (candidates.length === 0) {
    console.log("\n(No additional providers detected; skipping fallback chain.)");
    return [];
  }
  console.log("\nDetected providers you can use as fallbacks:");
  candidates.forEach((p, idx) => {
    console.log(`  [${idx + 1}] ${providerLabel(p)}`);
  });
  const raw = (
    await rl.question("Comma-separated numbers, in fallback order (or blank for none): ")
  ).trim();
  if (raw.length === 0) return [];
  const indices = raw
    .split(",")
    .map((entry) => Number(entry.trim()))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= candidates.length);
  return indices.map((n) => candidates[n - 1]);
}

async function ensureCredentialFor(
  rl: readline.Interface,
  provider: RoutingProviderId,
  rows: AvailabilityRow[],
): Promise<{ envUpdates: Record<string, string> }> {
  const row = rows.find((r) => r.provider === provider);
  if (row?.hasCli || row?.hasEnv) {
    return { envUpdates: {} };
  }
  console.log(`\n${providerLabel(provider)} has no credential configured.`);
  const hint = getInstallHint(provider);
  const envName = ENV_KEY_FOR_PROVIDER[provider];
  if (!envName) {
    if (hint) console.log(`  ${hint}`);
    console.log("  Skipping (no env-key path for this provider).");
    return { envUpdates: {} };
  }
  const accept = await promptYesNo(rl, `Paste an API key for ${envName} now?`, true);
  if (!accept) {
    if (hint) console.log(`  ${hint}`);
    return { envUpdates: {} };
  }
  const value = await promptApiKey(rl, envName, hint);
  if (!value) return { envUpdates: {} };
  return { envUpdates: { [envName]: value } };
}

async function main(): Promise<void> {
  console.log("Readable setup\n--------------");
  const rows = await describeAvailability();
  printAvailabilityTable(rows);

  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    const primary = await pickPrimary(rl, rows);
    const primaryCred = await ensureCredentialFor(rl, primary, rows);

    const fallbacks = await pickFallbacks(rl, primary, rows);
    const fallbackCreds: Record<string, string> = {};
    for (const fb of fallbacks) {
      const result = await ensureCredentialFor(rl, fb, rows);
      Object.assign(fallbackCreds, result.envUpdates);
    }

    const allowedList = primary === "coding-agent" ? "" : [primary, ...fallbacks].join(",");
    const localAgentList =
      primary === "coding-agent"
        ? rows.find((r) => r.provider === "coding-agent")?.localAgents?.join(",") || "codex-cli"
        : undefined;

    let env = await readEnvFile();
    env = upsertEnvLine(env, "LLM_PROVIDER", primary);
    env = upsertEnvLine(env, "LLM_ALLOWED_PROVIDERS", allowedList);
    if (localAgentList) {
      env = upsertEnvLine(env, "LLM_LOCAL_AGENTS", localAgentList);
    }
    for (const [key, value] of Object.entries({
      ...primaryCred.envUpdates,
      ...fallbackCreds,
    })) {
      env = upsertEnvLine(env, key, value);
    }
    await writeEnvFile(env);

    console.log("\n✓ Wrote .env.local");
    console.log(`  LLM_PROVIDER=${primary}`);
    console.log(`  LLM_ALLOWED_PROVIDERS=${allowedList}`);
    if (localAgentList) {
      console.log(`  LLM_LOCAL_AGENTS=${localAgentList}`);
    }

    if (
      Object.keys(primaryCred.envUpdates).length === 0 &&
      !rows.find((r) => r.provider === primary)?.hasCli &&
      !rows.find((r) => r.provider === primary)?.hasEnv
    ) {
      console.log(
        `\n⚠ Primary provider ${primary} still has no credential. Calls will fail until you set it.`,
      );
    }
    console.log("\nNext: pnpm db:migrate && pnpm dev");
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error("[setup] failed:", error instanceof Error ? error.message : error);
  process.exit(1);
});
