#!/usr/bin/env node
/**
 * Renders AGENTS.md for every module from its module.manifest.json plus its
 * hand-written module.narrative.md.
 *
 * Pure function of committed repo content: no network, no LLM, no absolute
 * paths, no reads outside the repo. That is what lets `--check` be a CI gate —
 * a generator that depended on one machine's filesystem could never produce a
 * stable result, and a permanently red gate teaches everyone to ignore gates.
 *
 *   node scripts/modules/generate-agents.mjs           # write
 *   node scripts/modules/generate-agents.mjs --check    # fail on any diff
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

import { loadModules, REPO_ROOT } from "./modules.mjs";

const SIZE_BUDGET = 150;

function render(mod, byId) {
  const L = [];
  const kids = [...byId.values()].filter((m) => m.parent === mod.id);

  L.push(`# ${mod.id}`);
  L.push("");
  L.push(`> ${mod.goal}`);
  L.push("");
  L.push("<!-- Generated by scripts/modules/generate-agents.mjs from module.manifest.json");
  L.push("     and module.narrative.md. Edit those, not this file. -->");
  L.push("");

  if (mod.narrative) {
    L.push(mod.narrative.trim());
    L.push("");
  }

  L.push("## Interface");
  L.push("");
  L.push(`Entrypoint: \`${mod.interface.entrypoint}\``);
  if (mod.interface.exports?.length) {
    L.push("");
    L.push("Anything not listed here is internal to this module:");
    L.push("");
    for (const e of mod.interface.exports) L.push(`- \`${e}\``);
  }
  L.push("");

  if (kids.length) {
    L.push("## Children");
    L.push("");
    L.push("Route by goal — you should not need to open more than one.");
    L.push("");
    for (const k of kids.sort((a, b) => a.id.localeCompare(b.id))) {
      L.push(`- **${k.id}** (\`${k.path}\`) — ${k.goal}`);
    }
    L.push("");
  }

  if (mod.uses?.length) {
    L.push("## Uses");
    L.push("");
    L.push("Read only the *interface* of these — never their internals.");
    L.push("");
    for (const u of mod.uses.sort((a, b) => a.module.localeCompare(b.module))) {
      const kind =
        u.kind && u.kind !== "import"
          ? ` _(${u.kind}, declared only — not statically verified)_`
          : "";
      L.push(`- **${u.module}** via \`${u.via}\`${kind}`);
    }
    L.push("");
  }

  L.push("## Constraints");
  L.push("");
  L.push(
    "Work outside these has left this module. Stop and ask rather than widening the boundary.",
  );
  L.push("");
  for (const c of mod.constraints) L.push(`- ${c}`);
  L.push("");

  L.push("## Checks");
  L.push("");
  L.push("Green here means the bounded work is done — no need to run the whole repo.");
  L.push("");
  L.push("```bash");
  for (const c of mod.checks) L.push(c);
  L.push("```");
  L.push("");

  if (mod.stubs?.length) {
    L.push("## Deliberate holes");
    L.push("");
    L.push("These are on purpose. Do not mistake them for bugs.");
    L.push("");
    for (const s of mod.stubs) {
      L.push(`### \`${s.id}\``);
      L.push("");
      L.push(`**Why:** ${s.why}`);
      L.push("");
      L.push(`**What would close it:** ${s.contract.target}`);
      L.push("");
      if (s.contract.validation?.length) {
        L.push("```bash");
        for (const v of s.contract.validation) L.push(v);
        L.push("```");
        L.push("");
      }
    }
  }

  return (
    L.join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

const check = process.argv.includes("--check");
const { modules, byId } = loadModules();

let failed = 0;
let over = 0;
for (const mod of modules) {
  const out = join(REPO_ROOT, mod.path === "." ? "" : mod.path, "AGENTS.md");
  const next = render(mod, byId);
  const lines = next.split("\n").length;
  if (lines > SIZE_BUDGET) {
    over++;
    console.warn(
      `  over budget: ${mod.id} AGENTS.md is ${lines} lines (budget ${SIZE_BUDGET}). ` +
        `That is a signal to split the module, not to trim the doc.`,
    );
  }
  const prev = existsSync(out) ? readFileSync(out, "utf8") : null;
  if (prev === next) continue;
  if (check) {
    failed++;
    console.error(`  stale: ${relative(REPO_ROOT, out)}`);
  } else {
    writeFileSync(out, next);
    console.log(`  wrote ${relative(REPO_ROOT, out)}`);
  }
}

if (check && failed) {
  console.error(
    `\n${failed} AGENTS.md file(s) are stale. Run: node scripts/modules/generate-agents.mjs`,
  );
  process.exit(1);
}
console.log(
  check
    ? `AGENTS.md: ${modules.length} modules up to date${over ? `, ${over} over budget` : ""}`
    : `AGENTS.md: ${modules.length} modules rendered${over ? `, ${over} over budget` : ""}`,
);
